<?php

namespace Tests\Unit;

use App\Domain\Company\Models\Company;
use App\Domain\User\Models\User;
use Tests\TestCase;

/**
 * Class IndexPageTest.
 */
class IndexPageTest extends TestCase
{
    /**
     * @var \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|mixed
     */
    private $company;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->company = Company::factory()->create();
    }

    /** @test */
    public function it_should_not_accessible_for_guest(): void
    {
        $this->withExceptionHandling()->get($this->getRoute())->assertStatus(302);
    }

    /** @test */
    public function it_shuold_not_accessible_only_for_users(): void
    {
        // first user is admin
        $this->truncate(User::class);
        $user = User::factory()->count(2)->create()->get(1);

        $this->withExceptionHandling()->signIn($user)->get($this->getRoute())->assertStatus(403);
    }

    /** @test */
    public function admin_user_can_access_finance_page(): void
    {
        // first user is admin
        $this->withExceptionHandling()
            ->signIn(null, 'admin', $this->company->account)
            ->get($this->getRoute())
            ->assertStatus(200);
    }

    private function getRoute()
    {
        return route(
            'account.company.finance',
            ['company' => $this->company, 'accountId' => $this->company->account_id]
        );
    }
}
